# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

version = 1

[[annotations]]
path = [
    "**/*.md",
    "**/*.html",
    "**/*.scss"
]
SPDX-FileCopyrightText = [
    '2024 The Jekyll Team <https://jekyllrb.com/team/>',
    '2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
]
SPDX-License-Identifier = 'CC-BY-SA-4.0+'

[[annotations]]
path = [
    "Gemfile.lock"
]
SPDX-FileCopyrightText = "1970 Computer-generated data, no copyright"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "favicon.ico"
SPDX-FileCopyrightText = '2024 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'CC-BY-SA-4.0+'
